#pragma once

#include "engine/EngineTypes.h"
#include "engine/Smoother.h"
#include "engine/dsp/Curve.h"
#include "engine/dsp/WavetableBank.h"
#include "engine/modules/EngineModules.h"
#include "engine/voice/VoiceManager.h"

#include "params/ConfigManager.h"
#include "params/ParamHandle.h"
#include "params/ParamRegistry.h"
#include "params/SnapshotExchange.h"

#include <array>
#include <cstdint>
#include <memory>
#include <string>

namespace winerose {

// Keys of the "Global" registry. Each engine module exposes its keys like this, next to its
// registration code; UIs refer to parameters only by "<Module>.<key>" strings (PLAN.md §2).
namespace global_keys {
inline constexpr const char* module       = "Global";
inline constexpr const char* masterVolume = "masterVolume";
inline constexpr const char* quality      = "quality";
inline constexpr const char* polyphony    = "polyphony";
inline constexpr const char* bendUp       = "bendUp";
inline constexpr const char* bendDown     = "bendDown";
}

enum class Quality { Good = 0, High = 1, Ultra = 2 };

// Immutable non-automatable engine state, rebuilt on the message thread and adopted by the audio thread at
// block start (SPEC §5.3). Voices read through the CURRENT snapshot every block and never cache its tables.
struct EngineSnapshot {
    std::uint64_t revision = 0;
    std::array<std::shared_ptr<const dsp::WavetableBank>, voice::kOscCount> oscTables;   // Oscillator0..2
    std::array<std::shared_ptr<const dsp::CurveTable>, voice::kOscCount>    remapCurves;  // warp Remap 1/2
    std::shared_ptr<const dsp::WavetableBank> subTable;     // Oscillator4 shapes
    std::shared_ptr<const dsp::NoiseTables>   noiseTables;  // Oscillator3 sources
    std::shared_ptr<const dsp::WavetableBank> lfoShapes;    // fixed LFO shapes (Sine..Square)
    std::array<std::shared_ptr<const dsp::WavetableBank>, modulation::kLfoCount> lfoPaths;   // drawable shapes
    std::array<std::int16_t, modulation::kSlotCount> slotDest {};   // mod-matrix destination → target index (-1 = none)
};

/**
 * @class Engine
 * @brief The synth. JUCE-free; driven through POD types by whichever host adapter owns it (PLAN.md §1.3).
 *
 * Phases 1-3 (SPEC §5.4): oscillators A/B/C (unison, dual warp), noise, sub, Filter0, four envelopes
 * (Env0 = amplitude), ten LFOs, eight macros and the 64-slot mod matrix, 64-voice pool, Quality
 * oversampling, pitch bend.
 *
 * Block-size independence: process() splits the host block into chunks that end at MIDI events and at
 * every kControlBlock-sample boundary of the ABSOLUTE sample count. Parameters are read and modulation
 * evaluated only on those boundaries, so the output is identical whatever block sizes the host uses.
 */
class Engine {
public:
    explicit Engine(std::shared_ptr<ConfigManager> config);
    ~Engine();

    Engine(const Engine&) = delete;
    Engine& operator=(const Engine&) = delete;

    /** Non-realtime. Resets voices and the sample clock. */
    void prepare(double sampleRate, int maxBlockSize);

    /** Realtime. Any numSamples >= 0. Events must be sorted by sampleOffset (relative to this block). */
    void process(float* const* out, int numChannels, int numSamples,
                 const MidiEvent* events, int numEvents,
                 const TransportInfo& transport) noexcept;

    /** Realtime. Arp / clip MIDI out generated by the last process() call. */
    void drainMidiOut(MidiEventSink& sink) noexcept;

    int  latencySamples() const noexcept { return 0; }
    void reset() noexcept;

    /** Message thread: rebuild + publish the EngineSnapshot (matrix routing, curves, tables). Called by the
     *  control layer on batch end and whenever a string parameter (destination, curve) changes. */
    void publishSnapshot();

    /** Message thread: replace oscillator A/B/C's (index 0..2) wavetable; takes effect at the next block. */
    void setOscillatorTable(int index, std::shared_ptr<const dsp::WavetableBank> table);

    const MeterState& meters() const noexcept { return m_meters; }
    int    maxBlockSize() const noexcept { return m_maxBlockSize; }
    double sampleRate() const noexcept { return m_sampleRate; }
    int    activeVoiceCount() const noexcept { return m_voices.activeCount(); }

    const modules::EngineModules& modules() const noexcept { return *m_modules; }
    std::shared_ptr<ConfigManager> configManager() const { return m_config; }

private:
    void controlTick() noexcept;
    void handleMidi(const MidiEvent& e) noexcept;
    void advanceFreeLfos(int numSamples) noexcept;
    void adoptSnapshot() noexcept;

    std::shared_ptr<ConfigManager>          m_config;
    std::unique_ptr<ParamRegistry>          m_global;
    std::unique_ptr<modules::EngineModules> m_modules;

    ParamHandle    m_masterVolume, m_polyphony, m_quality, m_bendUp, m_bendDown;
    LinearSmoother m_masterGain;

    voice::VoiceManager    m_voices;
    voice::ControlContext  m_context;
    std::array<float, modules::ModTargets::kMaxTargets> m_base {};
    std::array<modules::SlotParams, modulation::kSlotCount> m_slots {};
    std::array<std::int16_t, modulation::kSlotCount> m_noSlots {};   // all -1: used before a snapshot exists
    int           m_polyphonyLimit = 16;
    std::uint64_t m_sampleClock = 0;
    float         m_pitchBendRaw = 0.0f;   // -1..1

    // Message-thread copies; published via the snapshot. Curve-derived tables are cached by their string.
    std::array<std::shared_ptr<const dsp::WavetableBank>, voice::kOscCount> m_oscTables;
    std::shared_ptr<const dsp::WavetableBank> m_subTable;
    std::shared_ptr<const dsp::NoiseTables>   m_noiseTables;
    std::shared_ptr<const dsp::WavetableBank> m_lfoShapes;
    std::array<std::string, modulation::kLfoCount> m_lfoPathText;
    std::array<std::shared_ptr<const dsp::WavetableBank>, modulation::kLfoCount> m_lfoPaths;
    std::array<std::string, voice::kOscCount> m_remapText;
    std::array<std::shared_ptr<const dsp::CurveTable>, voice::kOscCount> m_remapCurves;

    SnapshotExchange<EngineSnapshot> m_snapshots;
    std::uint64_t                    m_snapshotRevision = 0;
    const EngineSnapshot*            m_current = nullptr;   // audio thread: adopted this block

    MeterState m_meters;
    double     m_sampleRate   = 44100.0;
    int        m_maxBlockSize = 0;
};

} // namespace winerose
